/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proj3bd;

/**
 *
 * @author bernardold
 */
public class ProjFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProjFrame
     */
    public ProjFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        RelatorioPanel = new javax.swing.JPanel();
        tipoRelatorioLabel = new javax.swing.JLabel();
        tipoRelatorioComboBox = new javax.swing.JComboBox<>();
        atletaPanel = new javax.swing.JPanel();
        modalidadeLabel = new javax.swing.JLabel();
        modalidadeTextField = new javax.swing.JTextField();
        medicoLabel = new javax.swing.JLabel();
        medicoTextField = new javax.swing.JTextField();
        treinadorLabel = new javax.swing.JLabel();
        treinadorTextField = new javax.swing.JTextField();
        medicoPanel = new javax.swing.JPanel();
        modalidadeLabel1 = new javax.swing.JLabel();
        modalidadeTextField1 = new javax.swing.JTextField();
        medicoLabel1 = new javax.swing.JLabel();
        medicoTextField1 = new javax.swing.JTextField();
        treinadorLabel1 = new javax.swing.JLabel();
        treinadorTextField1 = new javax.swing.JTextField();
        treinoPanel = new javax.swing.JPanel();
        treinadorPanel = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 852, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        tipoRelatorioLabel.setText("Tipo de Relatório");

        tipoRelatorioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atletas", "Médicos", "Treino por Período", "Treinadores com atletas Irregulares" }));
        tipoRelatorioComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoRelatorioComboBoxActionPerformed(evt);
            }
        });

        atletaPanel.setVisible(false);

        modalidadeLabel.setText("Modalidade");

        modalidadeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modalidadeTextFieldActionPerformed(evt);
            }
        });

        medicoLabel.setText("Atendido por Dr(a).");

        medicoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicoTextFieldActionPerformed(evt);
            }
        });

        treinadorLabel.setText("Treinado por");

        treinadorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treinadorTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout atletaPanelLayout = new javax.swing.GroupLayout(atletaPanel);
        atletaPanel.setLayout(atletaPanelLayout);
        atletaPanelLayout.setHorizontalGroup(
            atletaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atletaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modalidadeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modalidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(medicoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(medicoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(treinadorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(treinadorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        atletaPanelLayout.setVerticalGroup(
            atletaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atletaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(atletaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modalidadeLabel)
                    .addComponent(modalidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medicoLabel)
                    .addComponent(medicoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(treinadorLabel)
                    .addComponent(treinadorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(444, Short.MAX_VALUE))
        );

        atletaPanel.setVisible(false);

        modalidadeLabel1.setText("Modalidade");

        modalidadeTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modalidadeTextField1ActionPerformed(evt);
            }
        });

        medicoLabel1.setText("Atendido por Dr(a).");

        medicoTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicoTextField1ActionPerformed(evt);
            }
        });

        treinadorLabel1.setText("Treinado por");

        treinadorTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treinadorTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout medicoPanelLayout = new javax.swing.GroupLayout(medicoPanel);
        medicoPanel.setLayout(medicoPanelLayout);
        medicoPanelLayout.setHorizontalGroup(
            medicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modalidadeLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modalidadeTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(medicoLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(medicoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(treinadorLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(treinadorTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        medicoPanelLayout.setVerticalGroup(
            medicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(medicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modalidadeLabel1)
                    .addComponent(modalidadeTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medicoLabel1)
                    .addComponent(medicoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(treinadorLabel1)
                    .addComponent(treinadorTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(432, Short.MAX_VALUE))
        );

        atletaPanel.setVisible(false);

        javax.swing.GroupLayout treinoPanelLayout = new javax.swing.GroupLayout(treinoPanel);
        treinoPanel.setLayout(treinoPanelLayout);
        treinoPanelLayout.setHorizontalGroup(
            treinoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        treinoPanelLayout.setVerticalGroup(
            treinoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        atletaPanel.setVisible(false);

        javax.swing.GroupLayout treinadorPanelLayout = new javax.swing.GroupLayout(treinadorPanel);
        treinadorPanel.setLayout(treinadorPanelLayout);
        treinadorPanelLayout.setHorizontalGroup(
            treinadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        treinadorPanelLayout.setVerticalGroup(
            treinadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout RelatorioPanelLayout = new javax.swing.GroupLayout(RelatorioPanel);
        RelatorioPanel.setLayout(RelatorioPanelLayout);
        RelatorioPanelLayout.setHorizontalGroup(
            RelatorioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RelatorioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RelatorioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RelatorioPanelLayout.createSequentialGroup()
                        .addComponent(tipoRelatorioLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipoRelatorioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 443, Short.MAX_VALUE))
                    .addComponent(atletaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(RelatorioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RelatorioPanelLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(medicoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
            .addGroup(RelatorioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RelatorioPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(treinoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(RelatorioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RelatorioPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(treinadorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        RelatorioPanelLayout.setVerticalGroup(
            RelatorioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RelatorioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RelatorioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoRelatorioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoRelatorioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atletaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(RelatorioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RelatorioPanelLayout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(medicoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(29, 29, 29)))
            .addGroup(RelatorioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RelatorioPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(treinoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(RelatorioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RelatorioPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(treinadorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Relatórios", RelatorioPanel);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("XXXII Olimpíada – Tóquio 2020");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoRelatorioComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoRelatorioComboBoxActionPerformed
        int sel = this.tipoRelatorioComboBox.getSelectedIndex();
        
        switch (sel) {
            case 0:     // Reltorio de Atleta
                this.atletaPanel.setVisible(true);
                this.medicoPanel.setVisible(false);
                this.treinoPanel.setVisible(false);
                this.treinadorPanel.setVisible(false);
                
                break;
            case 1:     // Relatorio de Medico
                this.atletaPanel.setVisible(false);
                this.medicoPanel.setVisible(true);
                this.treinoPanel.setVisible(false);
                this.treinadorPanel.setVisible(false);
                break;
            case 2:     // Relatorio de Treinos
                this.atletaPanel.setVisible(false);
                this.medicoPanel.setVisible(false);
                this.treinoPanel.setVisible(true);
                this.treinadorPanel.setVisible(false);
                break;
            case 3:     // Relatorio de Treinadores
                this.atletaPanel.setVisible(false);
                this.medicoPanel.setVisible(false);
                this.treinoPanel.setVisible(false);
                this.treinadorPanel.setVisible(true);
                break;
            default:
                // May not happen
                break;
        }
        
    }//GEN-LAST:event_tipoRelatorioComboBoxActionPerformed

    private void modalidadeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modalidadeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modalidadeTextFieldActionPerformed

    private void medicoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicoTextFieldActionPerformed

    private void treinadorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treinadorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_treinadorTextFieldActionPerformed

    private void modalidadeTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modalidadeTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modalidadeTextField1ActionPerformed

    private void medicoTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicoTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicoTextField1ActionPerformed

    private void treinadorTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treinadorTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_treinadorTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel RelatorioPanel;
    private javax.swing.JPanel atletaPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel medicoLabel;
    private javax.swing.JLabel medicoLabel1;
    private javax.swing.JPanel medicoPanel;
    private javax.swing.JTextField medicoTextField;
    private javax.swing.JTextField medicoTextField1;
    private javax.swing.JLabel modalidadeLabel;
    private javax.swing.JLabel modalidadeLabel1;
    private javax.swing.JTextField modalidadeTextField;
    private javax.swing.JTextField modalidadeTextField1;
    private javax.swing.JComboBox<String> tipoRelatorioComboBox;
    private javax.swing.JLabel tipoRelatorioLabel;
    private javax.swing.JLabel treinadorLabel;
    private javax.swing.JLabel treinadorLabel1;
    private javax.swing.JPanel treinadorPanel;
    private javax.swing.JTextField treinadorTextField;
    private javax.swing.JTextField treinadorTextField1;
    private javax.swing.JPanel treinoPanel;
    // End of variables declaration//GEN-END:variables
}
