/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proj3bd;

/**
 *
 * @author bernardold
 */
public class ProjFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProjFrame
     */
    public ProjFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        RelatorioPanel = new javax.swing.JPanel();
        tipoRelatorioLabel = new javax.swing.JLabel();
        tipoRelatorioComboBox = new javax.swing.JComboBox<>();
        atletaPanel = new javax.swing.JPanel();
        modalidadeLabel = new javax.swing.JLabel();
        modalidadeTextField = new javax.swing.JTextField();
        medicoLabel = new javax.swing.JLabel();
        medicoTextField = new javax.swing.JTextField();
        treinadorLabel = new javax.swing.JLabel();
        treinadorTextField = new javax.swing.JTextField();
        gerarAtletaBtn = new javax.swing.JButton();
        medicoPanel = new javax.swing.JPanel();
        qtdAtletaLabel = new javax.swing.JLabel();
        qtdAtletaTextField = new javax.swing.JTextField();
        nacaoLabel = new javax.swing.JLabel();
        nacaoTextField = new javax.swing.JTextField();
        gerarMedicoBtn = new javax.swing.JButton();
        treinoPanel = new javax.swing.JPanel();
        treinoLabel = new javax.swing.JLabel();
        treinadorPanel = new javax.swing.JPanel();
        labelTreinador = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel2.setText("T.B.D.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(707, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(487, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Primeira parte", jPanel1);

        tipoRelatorioLabel.setText("Tipo de Relatório");

        tipoRelatorioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atletas", "Médicos", "Treino por Período", "Treinadores com atletas Irregulares" }));
        tipoRelatorioComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoRelatorioComboBoxActionPerformed(evt);
            }
        });

        modalidadeLabel.setText("Modalidade");

        modalidadeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modalidadeTextFieldActionPerformed(evt);
            }
        });

        medicoLabel.setText("Atendido por Dr(a).");

        medicoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicoTextFieldActionPerformed(evt);
            }
        });

        treinadorLabel.setText("Treinado por");

        treinadorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treinadorTextFieldActionPerformed(evt);
            }
        });

        gerarAtletaBtn.setText("Gerar Relatório");
        gerarAtletaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarAtletaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout atletaPanelLayout = new javax.swing.GroupLayout(atletaPanel);
        atletaPanel.setLayout(atletaPanelLayout);
        atletaPanelLayout.setHorizontalGroup(
            atletaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atletaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modalidadeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modalidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(medicoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(medicoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(treinadorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(treinadorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(gerarAtletaBtn)
                .addContainerGap())
        );
        atletaPanelLayout.setVerticalGroup(
            atletaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atletaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(atletaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modalidadeLabel)
                    .addComponent(modalidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medicoLabel)
                    .addComponent(medicoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(treinadorLabel)
                    .addComponent(treinadorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gerarAtletaBtn))
                .addContainerGap(471, Short.MAX_VALUE))
        );

        medicoPanel.setVisible(false);

        qtdAtletaLabel.setText("Quantidade de atletas atendidos");

        qtdAtletaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtdAtletaTextFieldActionPerformed(evt);
            }
        });

        nacaoLabel.setText("País de Origem");

        nacaoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacaoTextFieldActionPerformed(evt);
            }
        });

        gerarMedicoBtn.setText("Gerar Relatório");
        gerarMedicoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarMedicoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout medicoPanelLayout = new javax.swing.GroupLayout(medicoPanel);
        medicoPanel.setLayout(medicoPanelLayout);
        medicoPanelLayout.setHorizontalGroup(
            medicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(qtdAtletaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtdAtletaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nacaoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nacaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(gerarMedicoBtn)
                .addContainerGap())
        );
        medicoPanelLayout.setVerticalGroup(
            medicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(medicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtdAtletaLabel)
                    .addComponent(qtdAtletaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nacaoLabel)
                    .addComponent(nacaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gerarMedicoBtn))
                .addContainerGap(471, Short.MAX_VALUE))
        );

        treinoPanel.setVisible(false);

        treinoLabel.setText("Relatório de Treino");

        javax.swing.GroupLayout treinoPanelLayout = new javax.swing.GroupLayout(treinoPanel);
        treinoPanel.setLayout(treinoPanelLayout);
        treinoPanelLayout.setHorizontalGroup(
            treinoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(treinoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(treinoLabel)
                .addContainerGap(715, Short.MAX_VALUE))
        );
        treinoPanelLayout.setVerticalGroup(
            treinoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(treinoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(treinoLabel)
                .addContainerGap(484, Short.MAX_VALUE))
        );

        treinadorPanel.setVisible(false);

        labelTreinador.setText("Relatório de Treinadores com atletas irregulares");

        javax.swing.GroupLayout treinadorPanelLayout = new javax.swing.GroupLayout(treinadorPanel);
        treinadorPanel.setLayout(treinadorPanelLayout);
        treinadorPanelLayout.setHorizontalGroup(
            treinadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(treinadorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTreinador)
                .addContainerGap(533, Short.MAX_VALUE))
        );
        treinadorPanelLayout.setVerticalGroup(
            treinadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(treinadorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTreinador)
                .addContainerGap(484, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RelatorioPanelLayout = new javax.swing.GroupLayout(RelatorioPanel);
        RelatorioPanel.setLayout(RelatorioPanelLayout);
        RelatorioPanelLayout.setHorizontalGroup(
            RelatorioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RelatorioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tipoRelatorioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tipoRelatorioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(449, Short.MAX_VALUE))
            .addGroup(RelatorioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RelatorioPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(atletaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(RelatorioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RelatorioPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(medicoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(RelatorioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RelatorioPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(treinoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(RelatorioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RelatorioPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(treinadorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        RelatorioPanelLayout.setVerticalGroup(
            RelatorioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RelatorioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RelatorioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoRelatorioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoRelatorioLabel))
                .addContainerGap(518, Short.MAX_VALUE))
            .addGroup(RelatorioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RelatorioPanelLayout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(atletaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(RelatorioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RelatorioPanelLayout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(medicoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(RelatorioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RelatorioPanelLayout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(treinoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(RelatorioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RelatorioPanelLayout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(treinadorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Relatórios", RelatorioPanel);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("XXXII Olimpíada – Tóquio 2020");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoRelatorioComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoRelatorioComboBoxActionPerformed
        int sel = this.tipoRelatorioComboBox.getSelectedIndex();
        
        switch (sel) {
            case 0:     // Reltorio de Atleta
                this.atletaPanel.setVisible(true);
                this.medicoPanel.setVisible(false);
                this.treinoPanel.setVisible(false);
                this.treinadorPanel.setVisible(false);
                
                break;
            case 1:     // Relatorio de Medico
                this.atletaPanel.setVisible(false);
                this.medicoPanel.setVisible(true);
                this.treinoPanel.setVisible(false);
                this.treinadorPanel.setVisible(false);
                break;
            case 2:     // Relatorio de Treinos
                this.atletaPanel.setVisible(false);
                this.medicoPanel.setVisible(false);
                this.treinoPanel.setVisible(true);
                this.treinadorPanel.setVisible(false);
                break;
            case 3:     // Relatorio de Treinadores
                this.atletaPanel.setVisible(false);
                this.medicoPanel.setVisible(false);
                this.treinoPanel.setVisible(false);
                this.treinadorPanel.setVisible(true);
                break;
            default:
                // May not happen
                break;
        }
        
    }//GEN-LAST:event_tipoRelatorioComboBoxActionPerformed

    private void modalidadeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modalidadeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modalidadeTextFieldActionPerformed

    private void medicoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicoTextFieldActionPerformed

    private void treinadorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treinadorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_treinadorTextFieldActionPerformed

    private void qtdAtletaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtdAtletaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtdAtletaTextFieldActionPerformed

    private void nacaoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacaoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nacaoTextFieldActionPerformed

    private void gerarAtletaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarAtletaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gerarAtletaBtnActionPerformed

    private void gerarMedicoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarMedicoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gerarMedicoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel RelatorioPanel;
    private javax.swing.JPanel atletaPanel;
    private javax.swing.JButton gerarAtletaBtn;
    private javax.swing.JButton gerarMedicoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelTreinador;
    private javax.swing.JLabel medicoLabel;
    private javax.swing.JPanel medicoPanel;
    private javax.swing.JTextField medicoTextField;
    private javax.swing.JLabel modalidadeLabel;
    private javax.swing.JTextField modalidadeTextField;
    private javax.swing.JLabel nacaoLabel;
    private javax.swing.JTextField nacaoTextField;
    private javax.swing.JLabel qtdAtletaLabel;
    private javax.swing.JTextField qtdAtletaTextField;
    private javax.swing.JComboBox<String> tipoRelatorioComboBox;
    private javax.swing.JLabel tipoRelatorioLabel;
    private javax.swing.JLabel treinadorLabel;
    private javax.swing.JPanel treinadorPanel;
    private javax.swing.JTextField treinadorTextField;
    private javax.swing.JLabel treinoLabel;
    private javax.swing.JPanel treinoPanel;
    // End of variables declaration//GEN-END:variables
}
